/* Generated by scripts/build-email-templates.mjs. Do not edit. */

import * as abandonedCart from './abandoned-cart'
import * as affiliateInvitation from './affiliate-invitation'
import * as corporateFollowup from './corporate-followup'
import * as delivered from './delivered'
import * as giftCard from './gift-card'
import * as orderConfirmation from './order-confirmation'
import * as paymentConfirmation from './payment-confirmation'
import * as preparingOrder from './preparing-order'
import * as reviewRequest from './review-request'
import * as seasonalTemplate from './seasonal-template'
import * as shareYourGarden from './share-your-garden'
import * as shipping from './shipping'
import * as welcome from './welcome'

export interface EmailTemplate {
  readonly subject: string
  readonly html: string
}

export const templates = {
  "abandoned-cart": abandonedCart,
  "affiliate-invitation": affiliateInvitation,
  "corporate-followup": corporateFollowup,
  "delivered": delivered,
  "gift-card": giftCard,
  "order-confirmation": orderConfirmation,
  "payment-confirmation": paymentConfirmation,
  "preparing-order": preparingOrder,
  "review-request": reviewRequest,
  "seasonal-template": seasonalTemplate,
  "share-your-garden": shareYourGarden,
  "shipping": shipping,
  "welcome": welcome,
} as const satisfies Record<string, EmailTemplate>

export type TemplateName = keyof typeof templates
